// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCart(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetCart(ctx context.Context, id int64) (Cart, error)
	GetQuantity(ctx context.Context, id int64) (int64, error)
	GetQuantityForUpdate(ctx context.Context, id int64) (int64, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserForUpdate(ctx context.Context, username string) (User, error)
	UpdateCart(ctx context.Context, arg UpdateCartParams) (Cart, error)
}

var _ Querier = (*Queries)(nil)
